# Generated by Django 4.2.9 on 2024-01-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_paymentmodel_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='reservation',
        ),
    ]
