# Generated by Django 4.2.9 on 2024-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='checkInDateandTime',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='payment',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='preference',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
