# Generated by Django 4.2.9 on 2024-01-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutmodel_checkindateandtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='room',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
