# Generated by Django 4.2.9 on 2024-01-21 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_checkoutmodel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='reservation',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
