# Generated by Django 4.2.9 on 2024-01-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_checkoutmodel_reservation_checkoutmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='amount',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='reference_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
