# Generated by Django 4.2.9 on 2024-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customeruser', '0002_alter_custombaseuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/variac.jpeg/', null=True, upload_to='media'),
        ),
    ]
