# Generated by Django 4.2.9 on 2024-04-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customeruser', '0005_alter_custombaseuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/variac.jpeg/', null=True, upload_to='images/'),
        ),
    ]
