# Generated by Django 4.2.9 on 2024-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customeruser', '0012_alter_custombaseuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
