# Generated by Django 4.2.9 on 2024-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=150)),
                ('cardNo', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default='STATUS[0]', max_length=200)),
                ('files', models.FileField(upload_to='images')),
            ],
        ),
    ]
