# Generated by Django 4.2.9 on 2024-01-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='files',
        ),
        migrations.CreateModel(
            name='RoomfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('roommodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomapp.roommodel')),
            ],
        ),
    ]
