# Generated by Django 4.2.9 on 2024-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0002_remove_roommodel_files_roomfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
