# Generated by Django 4.2.9 on 2024-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0004_roommodel_bathroom_roommodel_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='profile_pic',
            field=models.ImageField(default='/Koala.jpg/', null=True, upload_to=''),
        ),
    ]
