# Generated by Django 4.2.9 on 2024-01-16 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting', models.CharField(choices=[('chandelier', 'chandelier'), ('Pendant Light', 'Pendant Light'), ('Track Light', 'Track Light'), ('Cabinet Light', 'Cabinet Light'), ('Accent Light', 'Accent Light'), ('Ceiling Light', 'Ceiling Light')], default='STATUS[0]', max_length=400, null=True)),
                ('bedspread', models.CharField(choices=[('Quilts,Coverlets,Blankets,Throwers,3-Pillows', 'Quilts,Coverlets,Blankets,Throwers,3-Pillows'), ('Coverlets,Blankets,Throwers,3-Pillows', 'Coverlets,Blankets,Throwers,3-Pillows'), ('Coverlets,Blankets,2-Pillows', 'Coverlets,Blankets,2-Pillows'), ('Coverlets,Throwers,3-Pillows', 'Coverlets,Throwers,3-Pillows')], default='STATUS[0]', max_length=400, null=True)),
                ('heater', models.BooleanField(default=False)),
                ('airconditioner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
