# Generated by Django 4.2.9 on 2024-01-21 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guestpreferenceapp', '0002_alter_preferencemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
