# Generated by Django 4.2.9 on 2024-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestpreferenceapp', '0003_alter_preferencemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='airconditioner',
            field=models.BooleanField(choices=[('on', 'True'), ('off', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='heater',
            field=models.BooleanField(choices=[('on', 'True'), ('off', 'False')], default=False),
        ),
    ]
