# Generated by Django 4.2.9 on 2024-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestpreferenceapp', '0009_alter_preferencemodel_airconditioner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='airconditioner',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='Boolean_choice[0]'),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='bedspread',
            field=models.CharField(choices=[('Quilts,Coverlets,Blankets,Throwers,3-Pillows', 'Quilts,Coverlets,Blankets,Throwers,3-Pillows'), ('Coverlets,Blankets,Throwers,3-Pillows', 'Coverlets,Blankets,Throwers,3-Pillows'), ('Coverlets,Blankets,2-Pillows', 'Coverlets,Blankets,2-Pillows'), ('Coverlets,Throwers,3-Pillows', 'Coverlets,Throwers,3-Pillows')], default='BEDSPREAD_CHOICE[0]', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='heater',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='Boolean_choice[0]'),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='lighting',
            field=models.CharField(choices=[('chandelier', 'chandelier'), ('Pendant Light', 'Pendant Light'), ('Track Light', 'Track Light'), ('Cabinet Light', 'Cabinet Light'), ('Accent Light', 'Accent Light'), ('Ceiling Light', 'Ceiling Light')], default='LIGHT_CHOICE[0]', max_length=400, null=True),
        ),
    ]
