# Generated by Django 4.2.9 on 2024-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestpreferenceapp', '0011_alter_preferencemodel_airconditioner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='airconditioner',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='preferencemodel',
            name='heater',
            field=models.BooleanField(),
        ),
    ]
