# Generated by Django 4.2.9 on 2024-01-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0002_remove_roommodel_files_roomfilemodel'),
        ('reservation', '0002_alter_reservationmodel_checkindateandtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='room',
        ),
        migrations.CreateModel(
            name='ReservedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationmodel')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roomapp.roommodel')),
            ],
        ),
    ]
