# Generated by Django 4.2.9 on 2024-01-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('reservation', '0003_remove_reservationmodel_room_reservedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.paymentmodel'),
        ),
    ]
