# Generated by Django 4.2.9 on 2024-01-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservationmodel_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='payment',
        ),
    ]
