# Generated by Django 4.2.9 on 2024-01-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0006_reservationmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='user',
            field=models.ForeignKey(limit_choices_to={'email': 'lesley@gmail.com'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
