# Generated by Django 4.2.9 on 2024-03-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestpreferenceapp', '0009_alter_preferencemodel_airconditioner_and_more'),
        ('reservation', '0010_alter_reservationmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guestpreferenceapp.preferencemodel'),
        ),
    ]
