# Generated by Django 4.2.9 on 2024-04-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservationmodel_checkindateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkInDateandTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
