# Generated by Django 4.2.9 on 2024-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reservationmodel_checkindateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='numberofdays',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
