# Generated by Django 4.2.9 on 2024-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_reservationmodel_numberofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='room',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
