# Generated by Django 4.2.9 on 2024-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_reservationmodel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkInDateandTime',
            field=models.DateTimeField(),
        ),
    ]
